import { 
  Home, 
  Card, 
  ArrowExchange, 
  Merchant, 
  Wallet, 
  Receipt, 
  Expense, 
  Groups, 
  BarChart 
} from "@revolut/icons";
import { Transaction } from "./types";

export const sidebarItems = [
  { icon: Home, label: "Home", active: true },
  { icon: Card, label: "Cards", hasDropdown: true },
  { icon: ArrowExchange, label: "Transfers", hasDropdown: true },
  { icon: Merchant, label: "Merchant", hasDropdown: true },
  { icon: Wallet, label: "Treasury" },
  { icon: Receipt, label: "Bills", hasDropdown: true },
  { icon: Expense, label: "Expenses" },
  { icon: Groups, label: "Team" },
  { icon: BarChart, label: "Analytics" },
];

export const transactions: Transaction[] = [
  {
    initials: "TG",
    name: "From Theodoros G",
    description: "Rent for April · Today, 17:07",
    amount: "+€540",
    status: "Completed",
    category: "Housing",
    type: "inflow",
    color: "bg-warning",
    reference: "Rent for April",
    date: "Today",
    time: "17:07",
    fees: "No fee",
    fromAccount: "Theodoros G",
    toAccount: "IPM - JOHN XENOFONTOS ...",
  },
  {
    initials: "AA",
    name: "From Antria A",
    description: "Sent from Revolut · Today, 16:21",
    amount: "+€600",
    status: "Completed",
    category: "Income",
    type: "inflow",
    img: "https://api.dicebear.com/7.x/avataaars/svg?seed=Antria",
    reference: "Monthly payment",
  },
  {
    initials: "HH",
    name: "To HILLSIDE HEIGHTS - Co...",
    description: "Today, 15:26",
    amount: "-€696",
    status: "Completed",
    category: "Housing",
    creator: "Andreas Giorkas",
    type: "outflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "IPM",
    name: "From IPM - HILLSIDE HEIG...",
    description: "Today, 15:26",
    amount: "+€696",
    status: "Completed",
    category: "Housing",
    creator: "Andreas Giorkas",
    type: "inflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "S",
    name: "Starbucks Coffee",
    description: "Cappuccino & Pastry · Yesterday, 09:15",
    amount: "-€12.40",
    status: "Completed",
    category: "Dining",
    type: "outflow",
    color: "bg-success",
  },
  {
    initials: "A",
    name: "Amazon.com",
    description: "Office Supplies · Yesterday, 14:30",
    amount: "-€145.99",
    status: "Completed",
    category: "Shopping",
    type: "outflow",
    color: "bg-shark",
  },
  {
    initials: "KM",
    name: "Money added from KENAA...",
    description: "February and March paym...",
    amount: "+€82",
    status: "Completed",
    category: "Income",
    type: "inflow",
    color: "bg-accent-primary",
  },
  {
    initials: "G",
    name: "Google Workspace",
    description: "Subscription · Apr 01, 2026",
    amount: "-€14.40",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "KM",
    name: "Money added from KOUTS...",
    description: "D3 947.04 + M8 1,354.80 +...",
    amount: "+€3,656.64",
    status: "Completed",
    category: "Income",
    type: "inflow",
    color: "bg-accent-primary",
  },
  {
    initials: "A",
    name: "Apple Store",
    description: "Software Upgrade · Mar 30, 2026",
    amount: "-€29.99",
    status: "Completed",
    category: "Shopping",
    type: "outflow",
    img: "https://api.dicebear.com/7.x/avataaars/svg?seed=Apple",
  },
  {
    initials: "DN",
    name: "From Dena N",
    description: "Koinoxrista 04/26 KOSTAS ...",
    amount: "+€27",
    status: "Completed",
    category: "Housing",
    type: "inflow",
    color: "bg-shark",
  },
  {
    initials: "M",
    name: "Microsoft Azure",
    description: "Cloud Services · Mar 28, 2026",
    amount: "-€452.12",
    status: "Completed",
    category: "Services",
    type: "outflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "O",
    name: "OpenAI API",
    description: "AI Usage Fees · Mar 27, 2026",
    amount: "-€120.00",
    status: "Completed",
    category: "Services",
    type: "outflow",
    color: "bg-success",
  },
  {
    initials: "H",
    name: "Hostinger International",
    description: "Web Hosting · Mar 25, 2026",
    amount: "-€89.90",
    status: "Completed",
    category: "Services",
    type: "outflow",
    color: "bg-accent-primary",
  },
  {
    initials: "R",
    name: "Refund from Revolut",
    description: "Overcharge correction · Mar 24, 2026",
    amount: "+€45.00",
    status: "Completed",
    category: "Refund",
    type: "inflow",
    color: "bg-warning",
  },
  {
    initials: "V",
    name: "Vercel Inc.",
    description: "Deployment Pro Plan · Mar 22, 2026",
    amount: "-€20.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-shark",
  },
  {
    initials: "S",
    name: "Spotify Technology",
    description: "Family Subscription · Mar 20, 2026",
    amount: "-€17.99",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-success",
  },
  {
    initials: "N",
    name: "Netflix.com",
    description: "Premium Plan · Mar 18, 2026",
    amount: "-€15.99",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-danger",
  },
  {
    initials: "G",
    name: "GitHub Inc.",
    description: "Copilot Subscription · Mar 15, 2026",
    amount: "-€10.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-shark",
  },
  {
    initials: "D",
    name: "DigitalOcean",
    description: "Droplet Services · Mar 12, 2026",
    amount: "-€40.00",
    status: "Completed",
    category: "Services",
    type: "outflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "F",
    name: "Figma Professional",
    description: "Editor Seat · Mar 10, 2026",
    amount: "-€15.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-warning",
  },
  {
    initials: "Z",
    name: "Zoom Video",
    description: "Pro Plan · Mar 08, 2026",
    amount: "-€13.99",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-accent-primary",
  },
  {
    initials: "U",
    name: "Uber Eats",
    description: "Dinner · Mar 05, 2026",
    amount: "-€34.50",
    status: "Completed",
    category: "Dining",
    type: "outflow",
    color: "bg-shark",
  },
  {
    initials: "L",
    name: "LinkedIn Premium",
    description: "Subscription · Mar 02, 2026",
    amount: "-€39.99",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "C",
    name: "Cloudflare",
    description: "Pro Plan · Mar 01, 2026",
    amount: "-€20.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-warning",
  },
  {
    initials: "W",
    name: "Wolters Kluwer",
    description: "Legal Research · Feb 28, 2026",
    amount: "-€245.00",
    status: "Completed",
    category: "Services",
    type: "outflow",
    color: "bg-accent-primary",
  },
  {
    initials: "S",
    name: "Slack Technologies",
    description: "Enterprise Subscription · Feb 25, 2026",
    amount: "-€150.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-success",
  },
  {
    initials: "A",
    name: "Adobe Creative Cloud",
    description: "All Apps Plan · Feb 22, 2026",
    amount: "-€59.99",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-danger",
  },
  {
    initials: "D",
    name: "Dropbox Inc.",
    description: "Storage Space · Feb 20, 2026",
    amount: "-€9.99",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-accent-vibrant",
  },
  {
    initials: "T",
    name: "Trello Gold",
    description: "Subscription · Feb 18, 2026",
    amount: "-€5.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-success",
  },
  {
    initials: "P",
    name: "Postman Inc.",
    description: "API Development Plan · Feb 15, 2026",
    amount: "-€12.00",
    status: "Completed",
    category: "Subscription",
    type: "outflow",
    color: "bg-warning",
  }
];
